import type { CurrencyCode } from '@/constants/currency';
import type { SpontaneousContext } from '@/types/imafima';
import type { CompanionOption, PersonalityOption, TripDurationOption } from '@/types/plan';
import type { UserPreferences } from '@/types/user-memory';
import type { TravelMemory } from '@/types/travel-memory';
import type { PlanCustomPreferences } from '@/types/plan-preferences';
import type { PlanCreationType } from '@/types/plan-creation';
import type { BestDayContext } from '@/types/best-day';
import type { WeatherForecast } from '@/lib/weather';

export type PlanAnalysisInput = {
  location: string;
  budget: string;
  currency: CurrencyCode;
  people: string;
  companion: CompanionOption;
  personality: PersonalityOption;
  tripDuration: TripDurationOption;
  tripDate: string;
  tripEndDate?: string;
  customDuration?: import('@/types/trip-schedule').CustomTripDuration;
  mood: string;
  customPreferences?: PlanCustomPreferences;
  weather?: WeatherForecast;
  userPreferences?: UserPreferences;
  travelMemories?: TravelMemory[];
  spontaneous?: SpontaneousContext;
  bestDay?: BestDayContext;
  planCreationType?: PlanCreationType;
  travelIntent?: string;
};
